# Generated by Django 6.1 on 2026-09-18 13:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esg', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pergunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=300)),
                ('pilar', models.CharField(choices=[('ambiental', 'Ambiental'), ('social', 'Social'), ('governanca', 'Governança')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Diagnostico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnosticos', to='esg.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='Resposta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('diagnostico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respostas', to='esg.diagnostico')),
                ('pergunta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='respostas', to='esg.pergunta')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('diagnostico', 'pergunta'), name='resposta_unica_por_pergunta_e_diagnostico')],
            },
        ),
    ]
